#!/usr/bin/env python3
from __future__ import annotations
import argparse
import ast
import difflib
import re
import shutil
from datetime import datetime
from pathlib import Path

OVERLAY_NAME = "v4z_canonicalise_fragment_core_flags_and_base_path_dominance"
CANONICAL_BLOCK = "# === BASE_PATH_WORKING_SET_DOMINANCE: start ===\n# Canonical local base-path dominance pruning.\n#\n# Active state tuple:\n#   (path, phase, onboard, E, t_depart, seenP, seenD, seenS, deliv_count, distance)\n#\n# The pruning hook is intentionally layer-local: enumerate_base_paths first builds the\n# full NewWork layer, then prunes dominated states immediately before Work = NewWork.\nBASE_PATH_WORKING_SET_DOMINANCE_ENABLED = os.getenv(\n    \"EVRP_BASE_PATH_WORKING_SET_DOMINANCE\", \"1\"\n).strip().lower() not in {\"0\", \"false\", \"no\", \"off\"}\nBASE_PATH_DOMINANCE_EPS = 1e-9\n\n\ndef _base_path_customer_skeleton(data, path):\n    return tuple(sid for sid in path if is_customer(data, sid))\n\n\ndef _base_path_state_key(data, state):\n    \"\"\"Structural key for local dominance within one base-path depth layer.\"\"\"\n    path, phase, onboard, E, t_depart, seenP, seenD, seenS, deliv_count, distance = state\n    return (\n        _base_path_customer_skeleton(data, path),\n        path[-1],\n        phase,\n        onboard,\n        seenP,\n        seenD,\n    )\n\n\ndef _base_path_state_metrics(state):\n    \"\"\"Comparable metrics for local dominance; lower tuple values are better.\"\"\"\n    path, phase, onboard, E, t_depart, seenP, seenD, seenS, deliv_count, distance = state\n    return (float(t_depart), float(distance), -float(E), len(onboard))\n\n\ndef _base_path_metrics_dominate(a_metrics, b_metrics, eps=BASE_PATH_DOMINANCE_EPS):\n    \"\"\"Return True if a is no worse than b and strictly better in at least one metric.\"\"\"\n    no_worse = all(a <= b + eps for a, b in zip(a_metrics, b_metrics))\n    strictly_better = any(a < b - eps for a, b in zip(a_metrics, b_metrics))\n    return no_worse and strictly_better\n\n\ndef _prune_base_path_working_set(data, work_states):\n    \"\"\"Prune dominated states from a completed NewWork layer.\"\"\"\n    if not BASE_PATH_WORKING_SET_DOMINANCE_ENABLED:\n        return work_states, {\n            \"enabled\": False,\n            \"input\": len(work_states),\n            \"output\": len(work_states),\n            \"dominated_removed\": 0,\n            \"keys\": 0,\n            \"max_bucket_size\": 0,\n        }\n\n    buckets = {}\n    for state in work_states:\n        buckets.setdefault(_base_path_state_key(data, state), []).append(state)\n\n    kept = []\n    dominated_removed = 0\n    max_bucket_size = 0\n    for group in buckets.values():\n        max_bucket_size = max(max_bucket_size, len(group))\n        nondominated = []\n        for candidate in group:\n            cand_metrics = _base_path_state_metrics(candidate)\n            if any(\n                _base_path_metrics_dominate(_base_path_state_metrics(existing), cand_metrics)\n                for existing in nondominated\n            ):\n                dominated_removed += 1\n                continue\n\n            survivors = []\n            for existing in nondominated:\n                if _base_path_metrics_dominate(cand_metrics, _base_path_state_metrics(existing)):\n                    dominated_removed += 1\n                    continue\n                survivors.append(existing)\n            survivors.append(candidate)\n            nondominated = survivors\n        kept.extend(nondominated)\n\n    return kept, {\n        \"enabled\": True,\n        \"input\": len(work_states),\n        \"output\": len(kept),\n        \"dominated_removed\": dominated_removed,\n        \"keys\": len(buckets),\n        \"max_bucket_size\": max_bucket_size,\n    }\n\n\ndef _print_base_path_dominance_event(depth, before, after, removed, keys=0, max_bucket_size=0, source=\"local_newwork\"):\n    print(\n        \"[BASE-PATH-DOMINANCE] \"\n        f\"source={source} depth={depth} before={before} after={after} \"\n        f\"removed={removed} keys={keys} max_bucket_size={max_bucket_size}\",\n        flush=True,\n    )\n\n\n# Backwards-compatible name retained because enumerate_base_paths may already call it.\n_bp_print_dominance_event = _print_base_path_dominance_event\n# === BASE_PATH_WORKING_SET_DOMINANCE: end ===\n"
OLD_HEADER = "\"\"\"Mechanically extracted fragment layer\nGenerated by experiments.build_consolidated_v1a_fragments.\nSource module is evrp_fragments_consolidated_v1/legacy_core.py.\n\"\"\""
NEW_HEADER = "\"\"\"Fragment generation and dominance-filtering layer.\n\nOriginally mechanically extracted from the consolidated legacy module. This module\nis now maintained directly as the active fragment-generation implementation.\n\"\"\""

START_MARKERS = [
    "# === BASE_PATH_WORKING_SET_DOMINANCE_PRUNING_APPLIED: start ===",
    "## === BASE_PATH_WORKING_SET_DOMINANCE_PRUNING_APPLIED: start ===",
    "# === BASE_PATH_WORKING_SET_DOMINANCE: start ===",
]
END_MARKERS = [
    "# === BASE_PATH_WORKING_SET_DOMINANCE_PRUNING_APPLIED: end ===",
    "## === BASE_PATH_WORKING_SET_DOMINANCE_PRUNING_APPLIED: end ===",
    "# === BASE_PATH_WORKING_SET_DOMINANCE: end ===",
]
STALE_SYMBOLS = [
    "FRAGMENT_CORE_GENERATED",
    "DEBUG_CALLBACK",
    "DEBUG_DIAGNOSTICS",
    "FORCE_CHAIN",
    "RUN_OPTIONA",
    "DIAG_SKELETON",
    "BASE_PATH_STEP_DOMINANCE_ENABLED",
    "_BASE_PATH_STEP_DOMINANCE_BUCKETS",
    "_BASE_PATH_STEP_DOMINANCE_STATS",
    "_BASE_PATH_STEP_DOMINANCE_PRINT_INTERVAL",
    "_BASE_PATH_ORIGINAL_STEP",
    "def _bp_tuple_field",
    "def _bp_state_get",
    "def _bp_normalise_set",
    "def _bp_state_seq",
    "def _bp_current_sid",
    "def _bp_metric_tuple",
    "def _bp_metric_dominates",
    "def _bp_state_dominance_key",
    "def _bp_step_depth_from_state",
    "def _bp_step_candidate_is_dominated",
]


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _write(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def _parse_ok(text: str):
    try:
        ast.parse(text)
    except SyntaxError as exc:
        return False, f"{type(exc).__name__}: {exc}"
    return True, None


def _line_index(lines, markers):
    marker_set = {m.strip() for m in markers}
    for idx, line in enumerate(lines):
        if line.strip() in marker_set:
            return idx
    return None


def _replace_dominance_block(text: str):
    lines = text.splitlines()
    start = _line_index(lines, START_MARKERS)
    end = _line_index(lines, END_MARKERS)
    if start is None or end is None or end < start:
        raise RuntimeError("Could not locate base-path dominance block markers")
    block_lines = CANONICAL_BLOCK.strip("\n").splitlines()
    new_lines = lines[:start] + block_lines + lines[end + 1:]
    return "\n".join(new_lines) + ("\n" if text.endswith("\n") else ""), start + 1, end + 1


def _canonicalise_header(text: str):
    if OLD_HEADER in text:
        return text.replace(OLD_HEADER, NEW_HEADER, 1), True
    return text, False


def _remove_simple_stale_globals(text: str):
    patterns = [
        r'^FRAGMENT_CORE_GENERATED\s*=.*\n',
        r'^DEBUG_CALLBACK\s*=.*\n',
        r'^DEBUG_DIAGNOSTICS\s*=.*\n',
        r'^FORCE_CHAIN\s*=.*\n',
        r'^RUN_OPTIONA\s*=.*\n',
        r'^DIAG_SKELETON\s*=.*\n',
    ]
    total = 0
    out = text
    for pattern in patterns:
        out, n = re.subn(pattern, '', out, flags=re.MULTILINE)
        total += n
    return out, total


def _remaining_symbols(text: str):
    return [symbol for symbol in STALE_SYMBOLS if symbol in text]


def _validate_expected(text: str):
    return {
        "has_canonical_state_key": "def _base_path_state_key" in text,
        "has_canonical_metrics": "def _base_path_state_metrics" in text,
        "has_canonical_prune": "def _prune_base_path_working_set" in text,
        "has_print_alias": "_bp_print_dominance_event = _print_base_path_dominance_event" in text,
        "has_local_newwork_hook": "source='local_newwork'" in text or 'source="local_newwork"' in text,
        "step_dominance_removed": "BASE_PATH_STEP_DOMINANCE_ENABLED" not in text,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=OVERLAY_NAME)
    parser.add_argument("--audit-only", action="store_true")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent
    fragment_path = repo_root / "evrp_fragments" / "fragment_core.py"
    report_path = repo_root / f"{OVERLAY_NAME}_report.txt"
    report = [f"[{OVERLAY_NAME.upper()}]", f"repo_root={repo_root}", f"fragment_path={fragment_path}", f"audit_only={args.audit_only}"]

    if not fragment_path.exists():
        report.append("ERROR: evrp_fragments/fragment_core.py not found")
        print("\n".join(report)); return 2

    before = _read(fragment_path)
    before_ok, before_err = _parse_ok(before)
    report.append(f"before_fragment_core_ast_parse_ok={before_ok}")
    if before_err:
        report.append(f"before_fragment_core_ast_parse_error={before_err}")
    if not before_ok:
        print("\n".join(report)); return 3

    try:
        transformed, block_start, block_end = _replace_dominance_block(before)
        transformed, header_changed = _canonicalise_header(transformed)
        transformed, stale_globals_removed = _remove_simple_stale_globals(transformed)
    except Exception as exc:
        report.append(f"ERROR: transform_failed={type(exc).__name__}:{exc}")
        print("\n".join(report)); return 4

    after_ok, after_err = _parse_ok(transformed)
    report.append(f"after_fragment_core_ast_parse_ok={after_ok}")
    if after_err:
        report.append(f"after_fragment_core_ast_parse_error={after_err}")
    report.append(f"dominance_block_replaced_lines={block_start}-{block_end}")
    report.append(f"header_changed={header_changed}")
    report.append(f"stale_globals_removed={stale_globals_removed}")

    checks = _validate_expected(transformed)
    for key, value in checks.items():
        report.append(f"{key}={value}")

    remaining = _remaining_symbols(transformed)
    report.append(f"remaining_stale_symbol_count={len(remaining)}")
    if remaining:
        report.append("remaining_stale_symbols:")
        for symbol in remaining:
            report.append(f"- {symbol}")

    diff = list(difflib.unified_diff(before.splitlines(), transformed.splitlines(), fromfile="fragment_core.py.before", tofile="fragment_core.py.after", lineterm=""))
    report.append(f"fragment_core_changed={before != transformed}")
    report.append(f"fragment_core_diff_line_count={len(diff)}")
    if diff:
        report.append("fragment_core_diff_preview:")
        report.extend(diff[:260])
        if len(diff) > 260:
            report.append(f"... diff preview truncated; total_diff_lines={len(diff)}")

    if not after_ok:
        report.append("patch_written=False")
        report.append("ERROR: transformed fragment_core.py failed AST parse; no files written")
        print("\n".join(report)); return 5
    if not all(checks.values()):
        report.append("patch_written=False")
        report.append("ERROR: expected canonical dominance checks failed; no files written")
        print("\n".join(report)); return 6

    if args.audit_only:
        report.append("patch_written=False")
        report.append("scope_note=Audit only. No files modified.")
        print("\n".join(report)); return 0

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    if before != transformed:
        backup = fragment_path.with_name(f"fragment_core.py.bak_{OVERLAY_NAME}_{stamp}")
        shutil.copy2(fragment_path, backup)
        _write(fragment_path, transformed)
        report.append(f"fragment_core_backup_created={backup}")
        report.append("fragment_core_patch_written=True")
    else:
        report.append("fragment_core_backup_created=None")
        report.append("fragment_core_patch_written=False")

    report.append("patch_written=True")
    report.append("scope_note=Canonicalised base-path dominance helpers and removed known stale globals. Local NewWork pruning is preserved.")
    report.append("next_step=run c103C16 benchmark and c103C16_2 fragment profile as smoke checks")
    _write(report_path, "\n".join(report) + "\n")
    print("\n".join(report))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
