"""Mechanically extracted callback and DP layer for consolidated v1c.

Generated by experiments.build_consolidated_v1c_callback.
Source module is evrp_fragments_consolidated_v1/legacy_core.py.
Role: generated derived output / mechanical callback split.
Do not edit manually during parity consolidation.
"""

from __future__ import annotations

CALLBACK_CORE_GENERATED = True
CALLBACK_CORE_SOURCE = 'evrp_fragments_consolidated_v1\\legacy_core.py'
CALLBACK_CORE_SOURCE_SHA256 = '268a9af84b26b04b5669f5fecb58aa08ba01e1cdc8f7d58739ff37f28593f15e'

SOURCE_PATH = 'C:\\Users\\wjvalo\\OneDrive - Queensland Treasury\\Documents\\UQ\\7013\\proj\\New folder\\Fragments_PDPTWEV-Q\\ev_fragmentsv3.py'

SOURCE_PATH_POSIX = 'C:/Users/wjvalo/OneDrive - Queensland Treasury/Documents/UQ/7013/proj/New folder/Fragments_PDPTWEV-Q/ev_fragmentsv3.py'

SOURCE_SHA256 = 'e1db5b59971d852dc008ec6de1b9034ffb76b806092767222a95995d4f3950df'

import math

from pathlib import Path

import os

import gurobipy as gp

from time import perf_counter

import heapq

DEBUG = False

DEBUG_CALLBACK = False

DEBUG_DIAGNOSTICS = True

FORCE_CHAIN = False

RUN_OPTIONA = True

DIAG_SKELETON = False

DP_MAX_STATION_VISITS_PER_LEG = 6

DP_MAX_LABELS_PER_NODE = 500

def print_dp_path_structure(tag, data, dp_path, dp_dist):
    stations = [sid for sid in dp_path if is_station(data, sid)]
    print(f"[{tag}] DP distance = {dp_dist:.6f}")
    print(f"[{tag}] DP path = {list(dp_path)}")
    print(f"[{tag}] Stations used ({len(stations)}): {stations}")

def dp_leg_frontier_charge_to_full(data, u_sid, v_sid, t0, E0, max_station_visits=3):
    """
    Single skeleton leg u -> v, stations can be inserted.
    Returns a list of NONDOMINATED arrival labels at v.

    Each label is:
      (dist_leg, t_start_at_v, E_arr_at_v, path_tuple)

    Stations: always open (no TW).
    Destination v: TW enforced.
    Charging: if station visited, charge to full with time (CapE - E_arr)/rech.
    """
    sid_to_i = data['sid_to_i']
    dist_fn  = data['dist']
    tt_fn    = data['traveltime']
    en_fn    = data['energy']
    CapE     = data['CapE']
    rech     = data['rech']
    horizon  = data['horizon']

    v_i = sid_to_i[v_sid]
    v_ready = data['nodes'][v_i][6]
    v_due   = data['nodes'][v_i][7]

    station_sids = [data['nodes'][i][0] for i in data['S']]

    # PQ state: (dist_so_far, dep_time, -dep_energy, cur_sid, path_tuple, stations_used, visited_stations_frozenset)
    pq = []
    heapq.heappush(pq, (0.0, t0, -E0, u_sid, (u_sid,), 0, frozenset()))

    # nondominated labels per intermediate node (including stations): (dist, time, energy)
    best_at_node = {u_sid: [(0.0, t0, E0)]}

    # nondominated arrivals at v: (dist, t_start, E_arr, path)
    arrivals = []

    def dominates3(a, b, eps=1e-9):
        # a,b = (dist, time, energy)
        da, ta, ea = a
        db, tb, eb = b
        return (da <= db + eps) and (ta <= tb + eps) and (ea >= eb - eps)

    def keep_nondominated_list(L, newlab3):
        # keep nondominated in list of (d,t,e)
        for lab in L:
            if dominates3(lab, newlab3):
                return L, False
        out = [lab for lab in L if not dominates3(newlab3, lab)]
        out.append(newlab3)
        return out, True

    def dominates_arr(a, b, eps=1e-9):
        # a,b = (dist, t_start, E_arr, path)
        da, ta, ea, _ = a
        db, tb, eb, _ = b
        return (da <= db + eps) and (ta <= tb + eps) and (ea >= eb - eps)

    def keep_arrivals(arrivals, cand):
        for lab in arrivals:
            if dominates_arr(lab, cand):
                return arrivals
        out = [lab for lab in arrivals if not dominates_arr(cand, lab)]
        out.append(cand)
        # optional: sort for neatness
        out.sort(key=lambda x: (x[0], x[1], -x[2]))
        return out

    while pq:
        d_sofar, t_dep, negE, cur_sid, path, k, visitedS = heapq.heappop(pq)
        E_dep = -negE

        # Explore either go to v, or to a station (if budget remains)
        next_nodes = [v_sid]
        if k < max_station_visits:
            next_nodes += station_sids

        for nxt_sid in next_nodes:
            if nxt_sid == cur_sid:
                continue
            if nxt_sid in visitedS:
                continue

            ui = sid_to_i[cur_sid]
            ni = sid_to_i[nxt_sid]

            e_need = en_fn(ui, ni)
            if e_need > E_dep + 1e-9:
                continue

            t_arr = t_dep + tt_fn(ui, ni)
            E_arr = E_dep - e_need
            d_new = d_sofar + dist_fn(ui, ni)

            if nxt_sid == v_sid:
                t_start = max(t_arr, v_ready)
                if t_start > v_due + 1e-9:
                    continue
                cand = (d_new, t_start, E_arr, path + (nxt_sid,))
                arrivals = keep_arrivals(arrivals, cand)
                continue

            # station
            if t_arr > horizon + 1e-9:
                continue

            charge_time = (CapE - E_arr) / rech
            t_dep2 = t_arr + charge_time
            E_dep2 = CapE

            lab3 = (d_new, t_dep2, E_dep2)
            lst = best_at_node.get(nxt_sid, [])
            lst2, kept = keep_nondominated_list(lst, lab3)
            if not kept:
                continue
            best_at_node[nxt_sid] = lst2

            new_visitedS = visitedS | frozenset([nxt_sid])
            heapq.heappush(pq, (d_new, t_dep2, -E_dep2, nxt_sid, path + (nxt_sid,), k+1, new_visitedS))

    return arrivals

def dp_route_min_dist(data, skeleton_sids, t0=0.0, E0=None,
                  max_station_visits_per_leg=DP_MAX_STATION_VISITS_PER_LEG,
                  max_labels_per_node=DP_MAX_LABELS_PER_NODE):
    """
    Multi-leg DP over mandatory skeleton nodes (no stations in skeleton_sids).
    Returns:
      ok, best_dist, best_full_path_tuple, fail_index
    fail_index = i means failure on leg skeleton[i] -> skeleton[i+1].
    """
    if E0 is None:
        E0 = data['CapE']

    for sid in skeleton_sids:
        if is_station(data, sid):
            raise ValueError(f"skeleton contains station {sid}; filter stations out first")

    sid_to_i = data['sid_to_i']

    # label at mandatory node: (dist_so_far, dep_time, dep_energy, full_path_tuple)
    def dominates_label(a, b, eps=1e-9):
        da, ta, ea, _ = a
        db, tb, eb, _ = b
        return (da <= db + eps) and (ta <= tb + eps) and (ea >= eb - eps)

    def insert_label(L, newlab):
        for lab in L:
            if dominates_label(lab, newlab):
                return L
        out = [lab for lab in L if not dominates_label(newlab, lab)]
        out.append(newlab)
        out.sort(key=lambda x: (x[0], x[1], -x[2]))
        return out[:max_labels_per_node]

    start_sid = skeleton_sids[0]
    labels = {start_sid: [(0.0, t0, E0, (start_sid,))]}

    for i in range(len(skeleton_sids) - 1):
        u = skeleton_sids[i]
        v = skeleton_sids[i+1]

        next_labels_for_v = []

        for (d_sofar, t_dep, E_dep, path_sofar) in labels.get(u, []):
            arrivals = dp_leg_frontier_charge_to_full(
                data, u, v, t_dep, E_dep,
                max_station_visits=max_station_visits_per_leg
            )

            # each arrival is (d_leg, t_start_v, E_arr_v, path_leg)
            for (d_leg, t_start_v, E_arr_v, path_leg) in arrivals:
                # service at v
                v_i = sid_to_i[v]
                serv_v = data['nodes'][v_i][8]
                t_dep_v = t_start_v + serv_v
                E_dep_v = E_arr_v

                # stitch paths (avoid duplicating u)
                if path_sofar[-1] == path_leg[0]:
                    stitched = path_sofar + path_leg[1:]
                else:
                    stitched = path_sofar + path_leg

                newlab = (d_sofar + d_leg, t_dep_v, E_dep_v, stitched)
                next_labels_for_v.append(newlab)

        if not next_labels_for_v:
            return False, None, None, i  # failed on leg i

        L_v = []
        for lab in next_labels_for_v:
            L_v = insert_label(L_v, lab)
        labels[v] = L_v

    final_sid = skeleton_sids[-1]
    best = min(labels[final_sid], key=lambda x: (x[0], x[1], -x[2]))
    best_dist, best_t, best_E, best_path = best
    return True, best_dist, best_path, None

def callback(model, where, x_vars, arcs, node_id, depot_u, data, theta, M):
    if where != gp.GRB.Callback.MIPSOL:
        return

    # Selected arcs
    xsol = model.cbGetSolution(x_vars)
    choose = [a_id for a_id, val in xsol.items() if val > 0.5]
    if not choose:
        return

    # Build successor/predecessor on state nodes
    out_map = {}
    in_map = {}
    for a_id in choose:
        a = arcs[a_id]
        out_map.setdefault(a['u'], []).append(a_id)
        in_map.setdefault(a['v'], []).append(a_id)

    # find cycles that don't touch depot. track visited nodes from depot and see if any chosen arc lies outside.
    seen_nodes = set([depot_u])
    stack = [depot_u]
    while stack:
        n = stack.pop()
        for a_id in out_map.get(n, []):
            v = arcs[a_id]['v']
            if v not in seen_nodes:
                seen_nodes.add(v)
                stack.append(v)

    # any chosen arc with tail not reachable from depot implies a disconnected cycle or subtour
    bad_cycle_arcs = [a_id for a_id in choose if arcs[a_id]['u'] not in seen_nodes]
    if bad_cycle_arcs:
        # cut here b/c all arcs in that subtour can be selected together ie. |S| - 1
        model.cbLazy(gp.quicksum(x_vars[a_id] for a_id in bad_cycle_arcs) <= len(bad_cycle_arcs) - 1)
        return

    # extract routes starting from depot
    routes = []
    for a_id in out_map.get(depot_u, []):
        route = [a_id]
        cur = arcs[a_id]['v']
        # follow until depot (or dead end)
        while cur != depot_u:
            nxts = out_map.get(cur, [])
            if not nxts:
                break
            # integer solution should have 1 outgoing; if multiple, pick one (shouldn't happen)
            a_id2 = nxts[0]
            route.append(a_id2)
            cur = arcs[a_id2]['v']
            # safety against infinite loops
            if len(route) > len(choose) + 5:
                break
        routes.append(route)

    sid_to_i = data['sid_to_i']
    dist_fn = data['dist']

    # We'll compute DP-based feasibility/cost per route and aggregate delta_total across all routes
    delta_total = 0.0

    # Helper: build skeleton and edge->arc mapping from a route arc list
    def skeleton_and_cover(route_arc_ids):
        # Build the skeleton nodes in order (stations removed), and map each skeleton edge to the arc index that covers it
        cover_arc_index = []  # cover_arc_index[j] = index in route_arc_ids of arc covering edge j: skeleton[j]->skeleton[j+1]

        # Build per-arc skeleton subseqs and then align
        arc_skel = []
        for idx, a_idid in enumerate(route_arc_ids):
            seq = arcs[a_id]['seq']
            sk = [sid for sid in seq if not is_station(data, sid)]
            # sk should have at least start/end
            arc_skel.append((idx, sk))

        # Merge in order, tracking edge coverage by arc index
        # Start with first arc's skeleton
        if not arc_skel or not arc_skel[0][1]:
            return [], []

        skeleton = list(arc_skel[0][1])

        # edges in this first arc are covered by arc index 0
        for _ in range(len(skeleton) - 1):
            cover_arc_index.append(arc_skel[0][0])

        # Append subsequent arcs, avoiding duplicate join node
        for (aidx, sk) in arc_skel[1:]:
            if not sk:
                continue
            if skeleton and sk and skeleton[-1] == sk[0]:
                # append sk[1:]
                for sid in sk[1:]:
                    skeleton.append(sid)
                for _ in range(len(sk) - 1):
                    cover_arc_index.append(aidx)
            else:
                # discontinuity; still append
                for sid in sk:
                    skeleton.append(sid)
                for _ in range(len(sk) - 1):
                    cover_arc_index.append(aidx)

        return skeleton, cover_arc_index

    # --- process each route ---
    for route in routes:
        sid_seq = []
        for k, aid in enumerate(route):
            s = arc_by_id[aid]['seq']
            if k == 0:
                sid_seq = list(s)
            else:
                if sid_seq[-1] == s[0]:
                    sid_seq.extend(s[1:])
                else:
                    sid_seq.extend(s)
        skeleton = [sid for sid in sid_seq if not is_station(data, sid)]
        if len(skeleton) < 2:
            continue

        # Run multi-leg DP: station insertion allowed, objective min distance
        ok, dp_dist, dp_full_path, fail_i = dp_route_min_dist(
            data, skeleton, t0=0.0, E0=data['CapE'],
            max_station_visits_per_leg=DP_MAX_STATION_VISITS_PER_LEG,
            max_labels_per_node=DP_MAX_LABELS_PER_NODE
        )

        if DEBUG_CALLBACK:
            print("DP path:", dp_full_path)
            print("DP distance:", dp_dist)
            print("Stations used:", [s for s in dp_full_path if is_station(data, s)])
            print("Num stations:", sum(is_station(data, s) for s in dp_full_path))

        if not ok:
            # For now: cut the whole route (safe, not minimal).
            # Once everything is stable, we can tighten to minimal prefix.
            model.cbLazy(gp.quicksum(x_vars[aid] for aid in route) <= len(route) - 1)
            return

        # # Feasibility cut: minimal prefix up to failing edge fail_i
            # # fail_i corresponds to skeleton[fail_i] -> skeleton[fail_i+1]
            # # cover_arc_idx[j] gives arc-index covering edge j
            # # prefix must include all arcs up to arc-index cover_arc_idx[fail_i]
            # if fail_i is None or fail_i >= len(cover_arc_idx):
            #     # fallback: cut whole route
            #     S_prefix = route
            # else:
            #     max_arcpos = cover_arc_idx[fail_i]
            #     S_prefix = route[:max_arcpos + 1]
            # model.cbLazy(gp.quicksum(x_vars[aid] for aid in S_prefix) <= len(S_prefix) - 1)
            # return  # safe to return after adding a feasibility cut

        # Compute optimistic direct distance for skeleton (no stations)
        # direct_dist = 0.0
        # for u_sid, v_sid in zip(skeleton, skeleton[1:]):
        #     ui = sid_to_i[u_sid]
        #     vi = sid_to_i[v_sid]
        #     direct_dist += dist_fn(ui, vi)
        #
        # delta = dp_dist - direct_dist

        # Base cost consistent with master objective: sum of Df of chosen arcs on this route
        base_route_cost = 0.0
        for aid in route:
            base_route_cost += arcs[aid]['Df']

        delta = dp_dist - base_route_cost


        if DEBUG:
            print("CALLBACK: delta_total =", delta_total, "choose_arcs =", choose)

        if delta > 1e-6:
            delta_total += delta

    # --- Optimality cut for whole incumbent ---
    if delta_total > 1e-6:
        # Condition on selecting all chosen arcs
        S = choose
        model.cbLazy(theta >= delta_total - M*(len(S) - gp.quicksum(x_vars[a] for a in S)))

def extract_routes_from_solution(chosen_arc_ids, arc_by_id, depot_sid='D0'):
    # index chosen arcs by Start node
    start_map = {}
    for aid in chosen_arc_ids:
        a = arc_by_id[aid]
        start_map.setdefault(a['Start'], []).append(aid)

    routes = []

    # depot-starting arcs define routes
    for aid0 in start_map.get(depot_sid, []):
        route = [aid0]
        cur_aid = aid0
        cur_end = arc_by_id[cur_aid]['End']

        while cur_end != depot_sid:
            nexts = start_map.get(cur_end, [])
            if len(nexts) != 1:
                raise RuntimeError(
                    f"Ambiguous or missing continuation at {cur_end}: {nexts}"
                )
            cur_aid = nexts[0]
            route.append(cur_aid)
            cur_end = arc_by_id[cur_aid]['End']

        routes.append(route)

    return routes

def route_distance_from_sids(data, sid_seq):
    dist = data['dist']         # helper from read_instance
    sid_to_i = data['sid_to_i'] # SID -> node index
    total = 0.0
    for u_sid, v_sid in zip(sid_seq, sid_seq[1:]):
        ui = sid_to_i[u_sid]
        vi = sid_to_i[v_sid]
        total += dist(ui, vi)
    return total

def stitch_sid_sequence(route, arc_by_id):
    sid_seq = []
    for k, aid in enumerate(route):
        s = arc_by_id[aid]['seq']
        if k == 0:
            sid_seq = list(s)
        else:
            if sid_seq[-1] == s[0]:
                sid_seq.extend(s[1:])
            else:
                sid_seq.extend(s)
    return sid_seq

def simulate_route(data, sid_seq):
    st = (
        (0,),                 # path placeholder
        0,                    # time
        frozenset(),          # onboard
        data['CapE'],         # energy
        0.0,                  # cost
        frozenset(),          # visited pickups
        frozenset(),          # visited deliveries
        frozenset(),          # visited stations
        0,                    # last node
        0.0                   # slack
    )

    for sid in sid_seq[1:]:
        j = data['sid_to_i'][sid]
        st2, reason = step(data, st, j)
        if st2 is None:
            return False, sid, reason
        st = st2

    return True, None, None

