"""Mechanically extracted master layer for consolidated v1b.

Generated by experiments.build_consolidated_v1b_master.
Source module is evrp_fragments_consolidated_v1/legacy_core.py.
Role: generated derived output / mechanical master split.
Do not edit manually during parity consolidation.
"""

from __future__ import annotations

MASTER_CORE_GENERATED = True
MASTER_CORE_SOURCE = 'evrp_fragments_consolidated_v1\\legacy_core.py'
MASTER_CORE_SOURCE_SHA256 = '268a9af84b26b04b5669f5fecb58aa08ba01e1cdc8f7d58739ff37f28593f15e'

SOURCE_PATH = 'C:\\Users\\wjvalo\\OneDrive - Queensland Treasury\\Documents\\UQ\\7013\\proj\\New folder\\Fragments_PDPTWEV-Q\\ev_fragmentsv3.py'

SOURCE_PATH_POSIX = 'C:/Users/wjvalo/OneDrive - Queensland Treasury/Documents/UQ/7013/proj/New folder/Fragments_PDPTWEV-Q/ev_fragmentsv3.py'

SOURCE_SHA256 = 'e1db5b59971d852dc008ec6de1b9034ffb76b806092767222a95995d4f3950df'

import math

from pathlib import Path

import os

import gurobipy as gp

from time import perf_counter

import heapq

DEBUG = False

DEBUG_CALLBACK = False

DEBUG_DIAGNOSTICS = True

FORCE_CHAIN = False

RUN_OPTIONA = True

DIAG_SKELETON = False

DP_MAX_STATION_VISITS_PER_LEG = 6

DP_MAX_LABELS_PER_NODE = 500

def raw_depot_arcs(data):

    nodes = data['nodes']
    depot_sid = nodes[0][0]
    out = []

    for p in data['P']:
        p_sid = nodes[p][0]

        # Build a fragment dict
        seq = (depot_sid, p_sid)
        Tf, Ef, Lf = compute_T_E_L(data, seq)
        Df = compute_distance(data, seq)

        # depot parameters (many are empty)
        out.append({
            'seq': seq,
            'Start': depot_sid,
            'End': p_sid,
            'start_onboard': frozenset(),
            'end_onboard': frozenset({p_sid}),
            'contains_charge': False,
            'Tf': Tf,
            'Ef': Ef,
            'Lf': Lf,
            'Df': Df,
            'Emin': 0.0,
            'LocsC': frozenset(),
            'ext_to': p_sid,
            'ext_station': None,
            'ext_delivery': data['p2d'].get(p_sid),
        })
    return out

def build_network(ef_list):

    node_id = {}
    arcs = []

    # node for each unique location/onboard combination
    def get_node(loc_sid, onboard_fs):
        state = (loc_sid, onboard_fs)
        # assign unique combo with index
        if state not in node_id:
            node_id[state] = len(node_id)
        return node_id[state]

    # iterate through each fragment, create nodes based on start and end, then generate arc data
    for idx, f in enumerate(ef_list):
        u = get_node(f['Start'], f['start_onboard'])
        v = get_node(f['End'], f['end_onboard'])
        arcs.append({
            'seq': f['seq'],
            'Start': f['Start'],
            'End': f['End'],
            'start_onboard': f['start_onboard'],
            'end_onboard': f['end_onboard'],
            'id': idx,
            'u': u,
            'v': v,
            'Tf': float(f['Tf']),
            'Ef': float(f['Ef']),
            'Lf': float(f['Lf']),
            'Df': float(f['Df']),
            'Emin': float(f.get('Emin', f.get('min_start_energy', 0.0))),
            'LocsC': f.get('LocsC', frozenset()),
        })

    return node_id, arcs

def make_gurobi_env():

    wls_id = os.getenv("GRB_WLSACCESSID", "").strip()
    wls_secret = os.getenv("GRB_WLSSECRET", "").strip()
    lic = os.getenv("GRB_LICENSEID", "").strip()

    if wls_id and wls_secret and lic:
        params = {
            "WLSACCESSID": wls_id,
            "WLSSECRET": wls_secret,
            "LICENSEID": int(lic),
        }
        return gp.Env(params=params)

    # return default env if there is no licence
    return gp.Env()

def build_master_model(data, ef_undom, K_max, force_exact_K = False):

    # add start arcs to existing frags
    depot_arcs = raw_depot_arcs(data)
    all_frags = depot_arcs + list(ef_undom)

    # build state nodes + arc sets
    node_id, arcs = build_network(all_frags)

    # identify depot node (D0, empty onboard)
    depot_sid = data['nodes'][0][0]
    depot_node = (depot_sid, frozenset())
    if depot_node not in node_id:
        # ensure depot node exists even if no arcs created it
        node_id[depot_node] = len(node_id)
    depot_u = node_id[depot_node]

    # map which arcs enter a node
    in_arcs = {n: [] for n in node_id.values()}
    # which arcs leave a node
    out_arcs = {n: [] for n in node_id.values()}
    for a in arcs:
        out_arcs[a['u']].append(a['id'])
        in_arcs[a['v']].append(a['id'])

    # Pickup list by sid
    pickups = [data['nodes'][i][0] for i in data['P']]

    arc_visits_pickups = {}  # aid -> set of pickup SIDs visited by this arc

    for a in arcs:
        s = strip_stations(a['seq'],data)
        # exclude the first node to avoid boundary double-counting across consecutive arcs
        visited = set(s[1:])
        arc_visits_pickups[a['id']] = {sid for sid in visited if sid in pickups}

    # Map pickup sid -> arc ids that end at that pickup (across any onboard)
    end_at_pickup = {p: [] for p in pickups}
    for a in arcs:
        if a['End'] in end_at_pickup:
            end_at_pickup[a['End']].append(a['id'])

    arc_by_id = {a['id']: a for a in arcs}

    for p in pickups:
        good = 0
        for aid in end_at_pickup[p]:
            v = arc_by_id[aid]['v']
            if len(out_arcs[v]) > 0:
                good += 1

    # Create model (w/ licence)
    env = make_gurobi_env()
    m = gp.Model(env=env)

    X = {a['id']: m.addVar(vtype=gp.GRB.BINARY) for a in arcs}
    theta = m.addVar(vtype=gp.GRB.CONTINUOUS)

    for a in arcs:
        if 'Df' not in a:
            a['Df'] = compute_distance(data, a['seq'])

    # objective
    m.setObjective(gp.quicksum(a['Df'] * X[a['id']] for a in arcs) + theta, gp.GRB.MINIMIZE)

    # Flow conservation on all state nodes except depot node
    for n in node_id.values():
        if n == depot_u:
            continue
        m.addConstr(gp.quicksum(X[i] for i in in_arcs[n]) - gp.quicksum(X[i] for i in out_arcs[n]) == 0)
    #
    # Depot balance defines vehicle count y
    # Changes between <= and == for sweeping across all K
    if force_exact_K:
        m.addConstr(gp.quicksum(X[i] for i in out_arcs[depot_u]) == K_max)
        m.addConstr(gp.quicksum(X[i] for i in in_arcs[depot_u]) == K_max)
    else:
        m.addConstr(gp.quicksum(X[i] for i in out_arcs[depot_u]) <= K_max)
        m.addConstr(gp.quicksum(X[i] for i in in_arcs[depot_u]) <= K_max)

    # coverage: each pickup must be served once
    for p in pickups:
        m.addConstr(
            gp.quicksum(X[aid] for aid in arc_visits_pickups if p in arc_visits_pickups[aid]) == 1)

    M = max_dist(data)

    m.Params.LazyConstraints = 1
    m.Params.Threads = 1
    m.Params.OutputFlag = 0
    _time_limit_raw = os.getenv("EVRP_SOLVER_TIME_LIMIT_SEC", "").strip()
    if _time_limit_raw:
        try:
            _time_limit_sec = float(_time_limit_raw)
        except ValueError as exc:
            raise ValueError(f"EVRP_SOLVER_TIME_LIMIT_SEC must be numeric, got {_time_limit_raw!r}") from exc
        if _time_limit_sec > 0:
            m.Params.TimeLimit = _time_limit_sec
            print(f"[SOLVER-CONFIG] TimeLimit={_time_limit_sec}", flush=True)

    return m, X, arcs, node_id, depot_u, arc_by_id, theta, M

